---
- hosts: localhost
  become: true
  pre_tasks:
  - name: update repositories
    apt: update_cache=yes
    hange_when: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
