---
- hosts: localhost
  become: true
  pre_tasks:
      apt: update_cache=yes
      change_when: False

  tasks:
    - include: tasks/users.yml      
    - include: tasks/packages.yml
    - include: tasks/cron.yml  
